// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qykuvfqtcgwusashrsoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5a3V2ZnF0Y2d3dXNhc2hyc29jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NjUwMDQsImV4cCI6MjA5MTE0MTAwNH0.FIxOKDT_hGyd12vusLuRTcTSdpay7ZsNhc5cmA5rqKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});